### ISSUE TITLE
RAML API documentation

### ISSUE THREAD

**Issue by nrmehta** [Falkonry/support#16]
We need executable documentation of the Falkonry API in the [RAML 1.0 spec](http://docs.raml.org/specs/1.0/) The documentation should cover only the following APIs:
- [x] `GET /pipeline`
- [x] `GET /pipeline/{id}`
- [ ] `POST /pipeline`
- [ ] `DELETE /pipeline/{id}`
- [ ] `POST /pipeline/{id}/input`
- [ ] `GET /pipeline/{id}/output`
- [ ] `POST /pipeline/{id}/verification`
- [ ] `GET /pipeline/{id}/verification`

**Comment by nrmehta** [comment]
The [YAML/Swagger](https://github.com/Falkonry/insight/blob/master/projects/studio/docs/api/falkonry.yaml) spec can be used if necessary

**Comment by nrmehta** [comment]
Let's add example JSON for requests and responses. For the cases where we are using CSV input, let's use a simple 5-line CSV file. For the security scheme let's use passthrough.

**Comment by kathy-spector** [comment]
FYI on security.  The "passthrough" is a new part of the RAML 1.0 spec
which is not yet released.  The tool I am using supports RAML 0.8 so it is
not currently available to use.  We can probably make the x-custom security
type work for the RAML, but the generated quick test web pages don't seem
to work with it.  For now, I will leave the security as-is so we can play
with the quick test pages.  Once we decided to publish the final version we
can decide if we want to go with x-custom.

**Comment by jeegs6up** [comment]
This is now available in SDK documentation. We may need to create a new repo for this given the substantial amount of files.
