### ISSUE TITLE
Update tutorial documentation

### ISSUE THREAD

**Issue by phagunbaya** [Falkonry/support#24]
Following things need to be updated
- [x] Page title in breadcrumbs shows <no-title>. It should be Tutorials.
- [x] Concepts section needs to be updated
- [ ] Tutorial video should show new UI.

![screen shot 2016-09-06 at 6 40 30 pm](https://cloud.githubusercontent.com/assets/1146297/18274795/e090187c-7461-11e6-8d34-2cae1b6f403b.png)

**Comment by jeegs6up** [comment]
Closing. With substitute new ones.
